version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: payment_schema

    ports:
      - '3307:3306'
    volumes:
      - /data/mysql
    container_name: payment-service-db

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment-service:1.1
    depends_on:
      - mysql-db
    ports:
      - '9196:9196'
    volumes:
      - /data/payment-service-ms
    container_name: payment-service-ms

    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/payment_schema?allowPublicKeyRetrieval=true&useSSL=false'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test1234

